README.md

Maybe I'm wrong, but in the documentation, there is this exemple to precompile rails assets before rsyncing.
But the exemple use the server `release_path` and not the `local_release_path`.
An error will occur if the server release path is use because the folder doesn't exist
Using the `local_release_path`, bundler will precompile in the `.local_repo` release folder

Bundler precompile local path

---

lib/capistrano/bundle_rsync/git.rb

This is a fix you are using the repo_tree option from Capistrano 3.1

Deploy subfolder if the repo_tree option is used

---

lib/capistrano/bundle_rsync/config.rb

If `bundle_rsync_ssh_options` and `ssh_options are not configured, cap deploy fails.
```
$ bundle exec cap production deploy
..snip..
cap aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/path/to/vendor/bundle/ruby/2.2.0/gems/capistrano-bundle_rsync-0.4.0/lib/capistrano/bundle_rsync/config.rb:64:in `build_ssh_command'
/path/to/vendor/bundle/ruby/2.2.0/gems/capistrano-bundle_rsync-0.4.0/lib/capistrano/bundle_rsync/git.rb:41:in `block in rsync_release'
/path/to/vendor/bundle/ruby/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:438:in `call'
/path/to/vendor/bundle/ruby/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:438:in `call_with_index'
/path/to/vendor/bundle/ruby/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:250:in `block (3 levels) in work_in_threads' …
```

Fix undefined method `[]' for nil:NilClass

---

lib/capistrano/bundle_rsync/config.rb

The example `set :bundle_rsync_max_parallels, ENV['PARA']` written in README does not work. When I run `$ PARA=1 cap production deploy` , it raises ArgumentError as follow: `ENV['PARA']` returns "1" as String.
```
** Invoke bundle_rsync:rsync_release (first_time)
** Execute bundle_rsync:rsync_release
cap aborted!
ArgumentError: comparison of String with 1 failed
/usr/local/ruby/versions/2.2.0/lib/ruby/gems/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:183:in `each'
/usr/local/ruby/versions/2.2.0/lib/ruby/gems/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:183:in `min'
/usr/local/ruby/versions/2.2.0/lib/ruby/gems/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:183:in `map'
/usr/local/ruby/versions/2.2.0/lib/ruby/gems/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:154:in `each' …
```

Force :bundle_rsync_max_parallels to be integer

---

lib/capistrano/bundle_rsync/bundler.rb
lib/capistrano/bundle_rsync/git.rb
lib/capistrano/bundle_rsync/local_git.rb
lib/capistrano/bundle_rsync/scm.rb

This fixes `--hosts` and `--roles` options to work.
As you know, servers are filtered when execute is called in `on` block. But rsync is called in `run_locally` block not in `on`, so they are not filtered.

Filter servers when running rsync on local

---

lib/capistrano/bundle_rsync/bundler.rb

If `.bundle/config` already exists, I don't want to remove it.
So bundle config file location specified.
`BUNDLE_APP_CONFIG` used bundle ~> 1.0.0.rc.4

Not remove bundle config file

---

.rspec
README.md
capistrano-bundle_rsync.gemspec
lib/capistrano/bundle_rsync/bundler.rb
lib/capistrano/bundle_rsync/config.rb
spec/capistrano/bundle_rsync/config_spec.rb
spec/spec_helper.rb

This features enable users to install gems with --standalone option.
In my case, I have monitoring scripts and related gems managed in Gemfile. In production, running with `bundle exec` prefix or binstubbing is a little slow and uses cpu. So, Instead, loading bundler/setup.rb  which is created by --standalone is faster. 
ref. http://myronmars.to/n/dev-blog/2012/03/faster-test-boot-times-with-bundler-standalone is well described.

Support bundle install with --standalone option

---

lib/capistrano/bundle_rsync/local_git.rb

Hi sonots-san,
Thanks for your great gem. This is super "便利".
I'd like to set `repo_tree` with `local_git` as same as `git`. So I've made a little change to `local_git.rb`.
Please check it.

Support repo_tree with local_git

---

lib/capistrano/bundle_rsync/git.rb
lib/capistrano/bundle_rsync/local_git.rb

@sonots 
This patch can suppress long logs generated by `git ls-remote`, especially for repositories with many tags and branches.
Because the primary objective of `git ls-remote` used in capistrano-bundle_rsync is to check the access rights to `remote_url`, we can omit a number of remote refs by specifying HEAD as `<refs>` at the end of the command.
Although the default exit code of `git ls-remote` is always 0 regardless of matched refs, I think specifying `HEAD` as `<refs>` is fairly simple option for Git users.
Ref. https://git-scm.com/docs/git-ls-remote.html

Suppress log by filtering remote refs

---

lib/capistrano/bundle_rsync/git.rb

Hello,
I want add this small improvement.
With this change, one can clean up stale remote-tracking branches in local mirror repository that are already removed from the remote repository.
cf) https://git-scm.com/docs/git-remote#_commands

Modify command "git remote update" to use "--prune" option

---

README.md
lib/capistrano/tasks/bundle_rsync.rake

Run example code, failing below error.
```
$ bundle exec cap local_git deploy
[Deprecation Notice] `set :scm, :bundle_rsync` is deprecated.
To ensure this custom SCM will work with future versions of Capistrano,
please upgrade it to a version that uses the new SCM plugin mechanism
documented here:
http://capistranorb.com/documentation/advanced-features/custom-scm
00:00 bundle_rsync:check
01 git ls-remote /home/hkobayash/capistrano-bundle_rsync/example/try_rails4 HEAD
01 78656aba46a28872d1f5f0ae6196f7e5496e1817       HEAD
01 78656aba46a28872d1f5f0ae6196f7e5496e1817       refs/remotes/origin/HEAD
✔ 01 hkobayash@localhost 0.028s
02 mkdir -p /home/hkobayash/capistrano-bundle_rsync/example/.local_repo
✔ 02 hkobayash@localhost 0.001s
00:00 deploy:check:directories
01 mkdir -p …
```

local_git scm deploy failed

---

README.md
example/Capfile
example/config/deploy.rb
example/config/deploy/git.rb
example/config/deploy/local_git.rb
example/config/deploy/skip_bundle.rb
lib/capistrano/bundle_rsync/plugin.rb

This patch aims to support new capistrano plugin system with minimum changes.
BTW, If we can drop capistrano-3.6.x support on next release, I suggest change `Capistrano::BundleRsync` from module to subclass of `Capistrano::SCM::Plugin`, like [capistrano-puma](https://github.com/seuros/capistrano-puma).

Support capistrano-3.7

---

lib/capistrano/bundle_rsync/git.rb

I would like to use `rev-list` for annotated git tags.
This was originally introduced in https://github.com/capistrano/capistrano/pull/1339 and `--max-count=1`
is the only option used in the latest v3.8.1.
https://github.com/capistrano/capistrano/blob/v3.8.1/lib/capistrano/scm/git.rb#L72

Use rev-list instead of rev-parse in cases like annotated tag

---

README.md
lib/capistrano/bundle_rsync/bundler.rb
lib/capistrano/bundle_rsync/config.rb

I'd like to modify `bundle install --without` option.
I'm using a special group in Gemfile. I would not like to deploy the special group.

Modify bundle --without option

---

lib/capistrano/bundle_rsync/git.rb

Probably, strip-count is not enough.

Fix num_components by tree_repo

---

README.md
lib/capistrano/bundle_rsync/bundler.rb
lib/capistrano/bundle_rsync/config.rb

The `--jobs` option makes it possible to run `bundle install` in parallel and it helps to speed up deployment.
This modification works fine on my local.
I would appreciate it if you could review this PR.
Thank you.

Add `bundle --jobs` option

---

capistrano-bundle_rsync.gemspec

As bundler 2 is stable now, I would like to use it when developing capistrano-bundle_rsync.
In my local environment, `bundle exec rspec` is successful with `Bundler version 2.4.13`

Remove bundler version dependency for development

---

lib/capistrano/bundle_rsync/scm.rb

`rsync(1)` can specify multiple sources as arguments.
https://www.unix.com/man-page/redhat/1/rsync/
> rsync [OPTION]... SRC [SRC]... [USER@]HOST:DEST
By utilizing this feature, execution count of `rsync` can be reduced to 1 both for `bundle_rsync_config_files` and for `bundle_rsync_shared_dirs`.
This contributes to much faster deployment (locally) as well as simplified code structure.

Sync multiple files and directories simultaneously

---

lib/capistrano/bundle_rsync/bundler.rb

When we are updating Ruby version of a Repository by `.ruby-version` of `rbenv`, we have found out that `bundle` command does not work as expected.
This occurs when there is a difference of Ruby version between deploying application version and deployed application version.
Let's assume we have a repository with Ruby 3.0.6, and we are deploying an old version of the same repository with Ruby 2.6.2. In this case, the current `bundle` is being run from Ruby 3.0.6, which is not an intended behavior.
Fixing this issue is divided into 3 phase.
* Running `bundle`within `local_release_path`
* This allows `rbenv` to decide Ruby version based on what is being deployed.
* Clearing environment variables of `RBENV_VERSION` and `RBENV_DIR`
* In order to forget current ruby version, `RBENV_VERSION` is …

Allow capistrano-bundle_rsync to deploy different Ruby version correctly

---

lib/capistrano/bundle_rsync/bundler.rb

This fixes #29.
There were 2 kinds of bundler deprecation warnings.
This patch fixes both of them.
```
[DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env`
```
This can be fixed by calling `Bundler.with_unbundled_env` instead of `Bundler.with_clean_env`.
Since `with_unbundled_env` is introduced in Bundler 2.2, I have implemented switching capability to support wide range of Bundler version.
c.f. https://github.com/rubygems/rubygems/commit/2fab03301147d68fde6419c4297c97874fd82afd
I have confirmed the deployment is successful for the following Bundler versions.
* Bundler 1.17.3
* Bundler 2.3.26
```
01 [DEPRECATED] The `--deployment` flag is …
```

Fix bundler deprecation

---

lib/capistrano/bundle_rsync/git.rb
lib/capistrano/bundle_rsync/local_git.rb

`execute` in SSHKit raises exception unless `raise_on_non_zero_exit: false` option is explicitly specified.
Therefore, we can omit `exit 1` here.
c.f.
https://github.com/capistrano/capistrano/blob/31e142d56f8d894f28404fb225dcdbe7539bda18/lib/capistrano/scm/tasks/git.rake#L15-L22

Remove unnecessary exit 1 for execute failure

---

lib/capistrano/bundle_rsync/scm.rb

While I am reading the code, I thought this method is no longer required for abstract class.
Both of `Capistrano::BundleRsync::Git` and `Capistrano::Bund` do not implement this method.
Probably, it seems like that this is something left when developing this gem.
Also, `test` is a little bit ambiguous considering the `test` of `SSHKit`.
The grep result for the remaining code is as follows:
```
% ag 'test' lib
lib/capistrano/bundle_rsync/config.rb
118:      fetch(:bundle_rsync_bundle_without) || [:development, :test]
lib/capistrano/bundle_rsync/bundler.rb
9:          bundle_commands = if test :rbenv, 'version'
```

Remove unnecessary method from Capistrano::BundleRsync::SCM

---

lib/capistrano/bundle_rsync.rb
lib/capistrano/bundle_rsync/config.rb
lib/capistrano/bundle_rsync/defaults.rb
lib/capistrano/bundle_rsync/plugin.rb
spec/spec_helper.rb

Capistrano Plugin system requires SCM class to implement
`set_defaults` to set the default of settings by `set_if_empty` as follows.
https://github.com/capistrano/capistrano/blob/31e142d56f8d894f28404fb225dcdbe7539bda18/lib/capistrano/scm/git.rb#L8-L23
This patch makes `Capistrano::BundleRsync` to be compatible with the design.
In order to support the historical interface, both Plugin and `capistrano/bundle_rsync` loads the defaults via
`Capistrano::BundleRsync::Defaults.set_defaults`

More plugin support (`set_defaults`) for Capistrano 3.7+

---

README.md
lib/capistrano/bundle_rsync/git_turbo.rb
lib/capistrano/tasks/bundle_rsync.rake

I have implemented `:git_turbo` strategy for super-fast deployment.
This strategy utilizes Git Worktree, Hardlink, and Rsync.
Following are the procedures in this strategy.
1. Locally, checkout worktree to `.local_repo/git_turbo_worktree`.
2. Locally, copy hardlink files by `cp -al` from `.local_repo/git_turbo_worktree` to `local_release_path`.
3. Remotely, copy hardlink files by `cp -al` from last release to `release_path`.
4. Rsync files from `local_release_path` to remote `release_path`.
The hardlinked files minimize disk I/O usually required for making release directory.
Preserved content and file attributes minimize data transfer by `rsync`.
This strategy is most suitable for continuous deployment where the diff between consecutive releases is small.
I have tested the time to deploy …

Implement :git_turbo Strategy for Super-Fast Deployment

---

README.md
lib/capistrano/bundle_rsync/bundler.rb
lib/capistrano/bundle_rsync/config.rb
lib/capistrano/bundle_rsync/defaults.rb
lib/capistrano/bundle_rsync/scm.rb

Capistrano::BundleRsync assumes that the top directory of the repository is the app directory.
Therefore, this runs `bundle` commands and locates `config` directory and `.bundle/config` files there.
This is simple but cannot fully support repositories where app directory locates in the subdirectory from the top directory.
Unlike `:git_tree`, this feature even support apps which have dependency in other sub directories.
The main use cases of feature is to support multi-apps repository with shared directory.
e.g.
```
* api-server-1 (depends on shared)
* api-server-2 (depends on shared)
* html-server (depends on shared)
* shared
```

Add `bundle_rsync_app_path` to specify where to run bundle
